### ISSUE TITLE
filter Status on relevant Workflows!

### ISSUE THREAD

**Issue by DarkSideGeek** [jgraichen/redmine_dashboard#121]
We have several workflows in play, not purely for S/W Development. Generally speaking, a workflow for another dept such as Legal will never be active within a Dev project (and vice versa). Yet the Dashboard task board iterates through all possible Status, even if the relevant workflows that use those Status are not enabled for the Project. With many Workflows, all the Status labels run together and cannot be deciphered.

Rather than "foreach Status", Dashboard should do something like "foreach Status in each enabledWorkflow".

This applies to the 2.x stable branch, but probably was carried forward to the 3.x...

**Comment by Gumis91** [comment]
Hello,
I've hit the same issue you've mentioned. Luckily, after couple of hours running through code and learning Ruby and Redmine, I've managed to create a workaround which displays statuses only for those trackers which are active in selected project (other statuses are set as hidden). I wanted to take it further and show only those statuses which are actually reachable for active user, but failed miserably due to virtually no knowledge of Ruby and Redmine internals.

I'm pretty sure my code is extremely inneficient (I'm C# dev and this is my first contact with Ruby ;-)), but does it's job fairly enough. What you have to do is to paste given code before last end statement in /app/models/rdb_taskboard.rb:

      def hidden_columns
        _used_columns ||= []
           trackers.each do |tracker|
             _used_columns.concat(tracker.issue_status_ids)
        end
        _used_columns = _used_columns.uniq
        _all_columns = IssueStatus.sorted.map {|issue_status| issue_status.id }
        _columns_to_hide = _all_columns - _used_columns
        _columns_to_hide.collect {|status_id| "s#{status_id}"}
      end 

When you're done, in the same file edit line 34 (at the beginnig of build method) to look like that:

        options[:hide_columns] ||= hidden_columns

Hope this helps while waiting for proper implementation.
BTW, great plugin! It makes life of my team much easier.
