### ISSUE TITLE
Inappropriate trackers & status appearing when used with sub-projects

### ISSUE THREAD

**Issue by senguttuvang** [jgraichen/redmine_dashboard#130]
I have a main project and 3 sub-projects in it. All 3 sub-projects have their own trackers and statuses. When opening a sub-project's dasboard, it shows trackers and statuses from all projects. 

Worse, the dasboard allows transition of tasks from one status to another which is not allowed by in my redmine configuration

**Comment by mr-gosh** [comment]
Approved - we also activated this awesome plugin and recognized that "Issue Statuses" are displayed that are not configured for any Workflow in this project. 
It is also possible to drang'n drop issues to Statuses that are not available to this status, project or workflow.

is this something you are targeting in v3 or is this a bug that could be fixed in v2?

**Comment by KrzysztofI** [comment]
+1 -  plugin is very good, but steel show all statuses in system also all versions and users. Lists (users, versions, trackers, statuss) should limit to elements available in project and if checked to sub projects.
