### ISSUE TITLE
not work in 4.0.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [jgraichen/redmine_dashboard#139]
can u help us

**Comment by jgraichen** [comment]
Please follow the installation guide for v2: https://github.com/jgraichen/redmine_dashboard/blob/stable-v2/README.md#install.

If there are any errors please search closed issues, especially if you are using an appliance. Otherwise please open a new issue with your problem telling what you did, what you tried and what happend. Please provide log files and command output too.
