### ISSUE TITLE
No route matches for .css and .js files on development environment

### ISSUE THREAD

**Issue by victor-vc** [jgraichen/redmine_dashboard#368]
I have installed the plug-in on a Redmine **development** environment but the Dashboard page is rendered without CCS and JS. The log file shows many routing errors (see below). However, on  the same server on the **production** environment, the Dashboard page displays just fine. Do you have any explanation for why it's not correctly rendered on the development environment?

Development log errors (some of them):
```
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/stylesheets/dashboard.css"):
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/stylesheets/dashboard.ui.css"):
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/stylesheets/dashboard.taskboard.css"):
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/javascripts/jquery.autoellipsis.js"):
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/javascripts/jquery.total-storage.js"):
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard_linked/javascripts/dashboard.js"):
```
Here is the info about the **development** environment.
```
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.0.5-p211 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Classic
SCM:
  Git                            2.39.2
  Filesystem                     
Redmine plugins:
  redmine_dashboard              2.12.4
```

**Comment by jgraichen** [comment]
Redmine only copies plugin assets into the public directory on server boot. Therefore, when doing development on the plugin, one has to restart Redmine after _any_ CSS or JS change. 

I've written a few utility scripts that install/update/configure local Redmine installations for development and testing (see `./redmine` and `./scripts/install`). They create a few symlinks, for example, to run tests and for assets:

```bash
if [ ! -L "${REDMINE_PATH}/public/plugin_assets/redmine_dashboard_linked" ]; then
  ln -s "${PLUGIN_PATH}/assets" "${REDMINE_PATH}/public/plugin_assets/redmine_dashboard_linked"
fi
```

The plugin will render different asset paths in _development_ mode to use the symlinked assets, that can just be edited and reloaded without having to restart the Redmine server process.

---

As the _development_ environment is only for developing on the Redmine or plugin code, this is expected behavior. If you want a testing/staging Redmine installation, please do use the production environment as well (see #337, #126).

**Comment by victor-vc** [comment]
Thanks for the reply. The development environment (setup) is for developing our own plug-ins. In order to perform full Redmine testing, we would like all the installed plug-ins to be working. Symlinking as described it in #337 fixed the "No route matches" errors.

**Comment by jgraichen** [comment]
Thanks for the explanation. That is indeed a valid use case for the development mode.

For running the plugin, you will only need the symlink for the assets. You can point it to either `public/plugin_assets/redmine_dashboard_linked` or `plugin/redmine_dashboard/assets`. All other symlinks are only needed for running Redmine Dashboard's own tests.
