### ISSUE TITLE
How to change dashboard item language?

### ISSUE THREAD

**Issue by paul09253336** [jgraichen/redmine_dashboard#493]
Hello everyone,

Recently, I built redmine 5.1 for my project. I successfully installed the dashboard plugin.

But I found that the dashboard items language is French. I want to change it to English or Chinese.

How to change dashboard project language?

![image](https://github.com/jgraichen/redmine_dashboard/assets/17095459/06d59bfa-ee0a-458b-9d16-382d1ca9258e)

**Comment by mingming-cn** [comment]
You can modify it in the issue status.

**Comment by jgraichen** [comment]
Hello @paul09253336,

These are your issue statuses defined by your administrator. The values are custom:

![image](https://github.com/jgraichen/redmine_dashboard/assets/800848/4e51c250-8692-4db4-808d-d389cd1dafaa)

Only the last column is translated because it groups all issue statuses marked as done.
