### ISSUE TITLE
Redmine 500 When clicking Dashboard

### ISSUE THREAD

**Issue by Defarine** [jgraichen/redmine_dashboard#82]
Hi,

I have just installed the dashboard, enabled it for a project and I have clicked on "Dashboard". Then I'm receiving error 500 with the following missing Database object.

Is an DB installtion/migration needed?

TinyTds::Error: Invalid object name 'rdb_sources'.: EXEC sp_executesql N'SELECT COUNT(*) FROM [rdb_sources] WHERE [rdb_sources].[context_id] = 1 AND [rdb_sources].[context_type] = N''Project'''

**Comment by Defarine** [comment]
I just have run a 
rake redmine:plugins:migrate RAILS_ENV=production


Now, I'm seeing this error:
TinyTds::Error: Cannot insert the value NULL into column 'updated_at', table 'redminedb.dbo.rdb_sources'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [rdb_sources] DEFAULT VALUES; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident'

**Comment by jgraichen** [comment]
First make sure you really want to use the current development version `3.0dev` as you are trying to install it. Stable version `2.0` does not need a database migration.

Second I've never seen the DBMS you're trying to use. It is supported by Rails and ActiveRecord? Because fields like `updated_at` are usually handled by Rails/ActiveRecord.
